# Generated by Django 3.2.8 on 2021-10-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_rooms_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='current_song',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
